### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by madoka-chann** [yzyyz1387/nonebot_plugin_heisi#4]
[error log.txt](https://github.com/yzyyz1387/nonebot_plugin_heisi/files/7870672/error.log.txt)

**Comment by yzyyz1387** [comment]
使用前请仔细阅读readme.md，该插件需要配置
>heisi_group=["123456","654321"] #黑丝白名单群号
heisi_cd=10 #黑丝cd时间（s）

**Comment by yzyyz1387** [comment]
经过测试，不配置`heisi_group`会出现上述问题
