### ISSUE TITLE
显示当前群未开通此功能

### ISSUE THREAD

**Issue by Kakaluoto** [yzyyz1387/nonebot_plugin_heisi#6]

**Comment by Kakaluoto** [comment]
03-04 12:58:49 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_heisi, type=message, priority=1, temp=False>
03-04 12:58:49 [DEBUG] nonebot | Running matcher <Matcher from nonebot_plugin_heisi, type=message, priority=1, temp=False>
03-04 12:58:49 [DEBUG] nonebot | Running handler <Dependent call=<function _ at 0x7ffab7d69280>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name='event', type=GroupMessageEvent, required=True)], parameterless=[]>
03-04 12:58:49 [INFO] nonebot_plugin_heisi | 群  ********* 未开通此功能，发送提示信息 
03-04 12:58:49 [DEBUG] nonebot | OneBot V11 | Calling API send_msg
03-04 12:58:50 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_heisi, type=message, priority=1, temp=False> running complete
03-04 12:58:50 [DEBUG] nonebot | Checking for matchers in priority 2...

**Comment by yzyyz1387** [comment]
按照readme配置了没，群号写进去没，不行就自己改源码

**Comment by Kakaluoto** [comment]
@yzyyz1387 多谢，已解决
