### ISSUE TITLE
按照流程走没问题，运行后报错

### ISSUE THREAD

**Issue by chongdong12** [yzyyz1387/nonebot_plugin_heisi#7]
在运行后提示报错： AttributeError: 'Config' object has no attribute 'heisi_group'，在.nev.dev中也配置了群号

**Comment by yzyyz1387** [comment]
请截图
![](https://cdn.jsdelivr.net/gh/yzyyz1387/blogimages/no_pic_say_jb.jpg)

**Comment by chongdong12** [comment]
> 请截图 ![](https://camo.githubusercontent.com/868955a9f964ec1500efb304f7238b339ea03de9f55fca0a90e2d390645e7244/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f797a79797a313338372f626c6f67696d616765732f6e6f5f7069635f7361795f6a622e6a7067)

奥 不好意思，刚才检查了一遍，在.nev里边没有写明配置文件是dev，但是在更改之后显示了如下报错
![QQ截图20220314192457](https://user-images.githubusercontent.com/95455587/158162733-b118b34f-3015-4999-8ee1-012a738eec6d.png)

**Comment by yzyyz1387** [comment]
你好，在.env中：
```
ENVIRONMENT=dev
```
表示正在使用的环境为`dev`，对应配置文件为`.env.dev`
此时针对此插件，应当做出的配置为(以我的测试环境为例)：
```
heisi_group=["237161342","313626291"] #黑丝白名单
heisi_cd=1 #黑丝cd时间（s）
```
若还不能解决，可以将`.env`、`.env.dev`截图上传此处再行探讨

**Comment by yzyyz1387** [comment]
若不想折腾，可直接下载插件代码加入自己的插件中

**Comment by chongdong12** [comment]
按照您的格式修改后，错误提示还是一样，如下是两个文件的截图
![QQ截图20220314192457](https://user-images.githubusercontent.com/95455587/158163838-9e6c5615-fabc-4415-ae32-d220f787430d.png)
![QQ截图20220314193300](https://user-images.githubusercontent.com/95455587/158163842-e7bd98d1-aeba-4e48-ad0e-c7c8f283c2bd.png)

**Comment by yzyyz1387** [comment]
抱歉你这边的问题我无法判断，经过我在本地多环境下多种情况测试，确实没有问题，或许你可以将插件源码copy到自己的环境下即可，实在抱歉

**Comment by chongdong12** [comment]
好的，很抱歉打扰到您了，我再多试几次，非常感谢

**Comment by yzyyz1387** [comment]
不会，很高兴你对此插件感兴趣，带来不好的体验实属抱歉，此issue将关闭![](https://api.isoyu.com/uploads/ARU/GIF_S/7220.gif)
